projects:
  DemoAPI:
    schemaPath: amplify/backend/api/DemoAPI/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: eu-central-1
        apiId: null
        maxDepth: 2
